### ISSUE TITLE
GitHub Actions: Replace matrix strategy with environment variable

### ISSUE THREAD

**Issue by jongwooo** [yorkie-team/yorkie#618]
**Description**:

proposal: **Replace matrix strategy with environment variable**

**Why**:

> **About matrix strategies** 
A **matrix strategy** lets you use variables in a **single job definition** to automatically create **multiple job** runs that are based on the combinations of the variables.

I think `matrix` is better for running multiple jobs; when running a single job, simply set the go version can be replaced with an `environment variable`. I've referenced the workflow in the link attached below: https://github.com/kubernetes/minikube/blob/master/.github/workflows/pr.yml#L13-L15

**AS-IS**

```yaml
jobs:
  build:
    name: build
    strategy:
      matrix:
        go_version:
          - 1.19.2
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
```

**TO-BE**

```yaml
env:
  GO_VERSION: '1.19.2'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
```
