### ISSUE TITLE
Run CI Only on Code Level Change PR

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie#873]
**Description**:

Adjusting CI configuration to trigger builds only on code-level changes.

Currently CI is running on every PR we are making.
This is because CI is configured to be triggered on every pull requests.

```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
...
```
We can adjust this configuration to trigger CI only on code level changes.
We do not have to run CI on other PR like documentation. 

This optimization should also be applied to other repositories as well.

**Why**:

Improving CI efficiency by avoiding unnecessary build runs on PRs without code changes.
